"""One-off generator for the app icon (resources/icon.ico + resources/IconData.h).
Re-run with `python generate_icon.py` after editing the constants below if the
design needs to change; this script itself is not part of the build.
"""

from PIL import Image, ImageDraw

# Colours pulled straight from Boggle.cpp's DrawBoard() so the icon matches the
# in-app tile/path rendering exactly.
TILE_FILL = (245, 222, 179, 255)     # tileColor
TILE_BORDER = (120, 120, 120, 255)   # tileBorderColor
PATH_COLOR = (232, 90, 90, 255)      # pathColor

SUPERSAMPLE = 4
BASE = 1024
SIZE = BASE * SUPERSAMPLE

MARGIN = int(SIZE * 0.06)
GAP = int(SIZE * 0.05)
TILE = (SIZE - 2 * MARGIN - GAP) // 2
TILE_RADIUS = int(TILE * 0.16)
BORDER_WIDTH = max(1, int(TILE * 0.035))

LINE_THICKNESS = int(SIZE * 0.107)

img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
draw = ImageDraw.Draw(img)

tiles = [
    (MARGIN, MARGIN),                                  # top-left
    (MARGIN + TILE + GAP, MARGIN),                      # top-right
    (MARGIN, MARGIN + TILE + GAP),                      # bottom-left
    (MARGIN + TILE + GAP, MARGIN + TILE + GAP),          # bottom-right
]

for (x, y) in tiles:
    box = (x, y, x + TILE, y + TILE)
    draw.rounded_rectangle(box, radius=TILE_RADIUS, fill=TILE_FILL)

for (x, y) in tiles:
    box = (x, y, x + TILE, y + TILE)
    draw.rounded_rectangle(box, radius=TILE_RADIUS, outline=TILE_BORDER, width=BORDER_WIDTH)

# Z-shaped path across the grid: three segments with rounded caps/joins, drawn
# the same way DrawSegment() in Boggle.cpp draws a selected word's path
# (thick line + filled circle at each end).
p1 = (SIZE * 0.214, SIZE * 0.286)
p2 = (SIZE * 0.821, SIZE * 0.286)
p3 = (SIZE * 0.161, SIZE * 0.696)
p4 = (SIZE * 0.839, SIZE * 0.696)

segments = [(p1, p2), (p2, p3), (p3, p4)]
radius = LINE_THICKNESS * 0.5

for a, b in segments:
    draw.line([a, b], fill=PATH_COLOR, width=LINE_THICKNESS)
    for (cx, cy) in (a, b):
        draw.ellipse((cx - radius, cy - radius, cx + radius, cy + radius), fill=PATH_COLOR)

master = img.resize((BASE, BASE), Image.LANCZOS)

# Windows .exe / taskbar icon.
ico_sizes = [16, 32, 48, 64, 128, 256]
master.save("icon.ico", sizes=[(s, s) for s in ico_sizes])

# Runtime title-bar icon (SDL_SetWindowIcon), embedded as raw RGBA so no image
# loader library is required at runtime.
RUNTIME_SIZE = 64
runtime = master.resize((RUNTIME_SIZE, RUNTIME_SIZE), Image.LANCZOS)
pixels = runtime.tobytes("raw", "RGBA")

with open("IconData.h", "w", newline="\n") as f:
    f.write("// Generated by Application/resources/generate_icon.py - do not edit by hand.\n")
    f.write("#pragma once\n\n")
    f.write("namespace App\n{\n")
    f.write(f"  constexpr int IconWidth = {RUNTIME_SIZE};\n")
    f.write(f"  constexpr int IconHeight = {RUNTIME_SIZE};\n\n")
    f.write("  // Raw RGBA8888 pixels, row-major, top-to-bottom.\n")
    f.write(f"  constexpr unsigned char IconPixels[{len(pixels)}] =\n  {{\n")
    for i in range(0, len(pixels), 20):
        row = pixels[i:i + 20]
        f.write("    " + ", ".join(str(b) for b in row) + ",\n")
    f.write("  };\n")
    f.write("}\n")

print("Wrote icon.ico and IconData.h")
